pool:
    name: Hosted macOS
    demands: xcode

trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    exclude:
    - README.md

pr:
  branches:
    include:
    - master

steps:
  - task: Xcode@5
    displayName: 'xcodebuild -showsdks'
    inputs:
      actions: '-showsdks'
      scheme: 'Trust'
      configuration: Release
      sdk: iphonesimulator13.2
      xcodeVersion: specifyPath
      xcodeDeveloperDir: '/Applications/Xcode_11.3.1.app/Contents/Developer'
  
  - script: |
     sudo gem install bundler simctl
     sudo bundle install
    workingDirectory: "$(Build.SourcesDirectory)/Example"
    displayName: 'Install gems'
  
  - task: Cache@2
    workingDirectory: "$(Build.SourcesDirectory)/Example"
    inputs:
      key: 'pod|Darwin|Podfile.lock'
      path: 'Pods'
      cacheHitVar: 'CacheRestored'
  
  - script: 'bundle exec pod install --repo-update'
    workingDirectory: "$(Build.SourcesDirectory)/Example"
    displayName: 'Pod install'
    enabled: true
    condition: ne(variables['CacheRestored'], 'true')
  
  - script: |
     bundle exec fastlane ios tests
    workingDirectory: "$(Build.SourcesDirectory)/Example"
    displayName: 'bundle exec fastlane ios tests'
